#INCLUDE <LIQUIDCRYSTAL.H>
LIQUIDCRYSTAL LCD(2, 3, 4, 5, 6, 7);
CONST INT HALLSENSORPIN = 5;
CONST UNSIGNED LONG SAMPLETIME = 1000;
INT RPMMAXIMUM = 0;
VOID SETUP()
{
	PINMODE(HALLSENSORPIN, INPUT);
	SERIAL.BEGIN(115200);
	LCD.BEGIN(16, 2);
	LCD.PRINT("WELCOME");
	DELAY(0);
	LCD.CLEAR();
}
VOID LOOP()
{
	DELAY(1000);
	INT RPM = GETRPM();
	LCD.CLEAR();
	SERIAL.PRINTLN(RPM);
	LCD.PRINT(RPM, DEC);
	//DISPLAYRPM(RPM);
}
INT GETRPM()
{
	INT COUNT = 0;
	BOOLEAN COUNTFLAG = LOW;
}
UNSIGNED LONG CURRENTTIME = 0;
UNSIGNED LONG STARTTIME = MILLIS();
WHILE(CURRENTTIME <= 1000)
{
	IF(DIGITALREAD(HALLSENSORPIN) == HIGH)
	{
		COUNTFLAG = HIGH;
	}
	UNSIGNED LONG CURRENTTIME = 0;
	UNSIGNED LONG STARTTIME = MILLIS();
	WHILE(CURRENTTIME <= 1000)
	{
		IF(DIGITALREAD(HALLSENSORPIN) == HIGH)
		{
			COUNTFLAG = HIGH;
		}
		IF(DIGITALREAD(HALLSENSORPIN) == LOW && COUNTFLAG == HIGH)
		{
			COUNT++;
			COUNTFLAG = LOW;
		}
		CURRENTTIME = MILLIS() - STARTTIME;
	}
	INT COUNTRPM = INT(60000 / CURRENTTIME) * COUNT;
	RETURN COUNTRPM;
}
VOID DISPLAYRPM(INT RPM)
{
	LCD.CLEAR();
	LCD.SETCURSOR(0, 0);
	LCD.PRINT("FLOW METER");
	LCD.SETCURSOR(0, 1);
	LCD.PRINT("RPM = ");
	LCD.PRINT(RPM, DEC);